[package]
name = "ishihara"
version = "0.1.0"
authors = ["Brennan Tracy <brennantracy4@gmail.com>"]
edition = "2021"

[dependencies]
getrandom = { version = "0.2", features = ["js"] }
gloo-events = "0.1"
gloo-render = "0.1"
gloo-timers = "0.2"
image = "0.23"
imageproc = "0.22"
js-sys = "0.3"
log = "0.4"
nom = "6.0"
rand = "0.8"
rusttype = "0.9"
wasm-bindgen = "0.2"
wasm-logger = "0.2"
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }

[dependencies.web-sys]
version = "0.3"
features = [
  'CanvasRenderingContext2d',
  'Document',
  'Element',
  'HtmlCanvasElement',
  'ImageData',
]

